# Config for logging
# ------------------
# See http://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema

logging:
    version: 1
    disable_existing_loggers: true

    root:
        level: !!python/name:logging.DEBUG
        handlers: [console, file, socket]

    loggers:
        # Top level logger (for tnt package)
        tntserver:
            level: !!python/name:logging.DEBUG
            handlers: [console, file, socket]
            qualname: tnt
            propagate: false
            filters: [patternfilter]
        matplotlib:
            level: !!python/name:logging.WARNING

    handlers:
        # Handler to write logs into file
        file:
            class: logging.handlers.RotatingFileHandler
            filename: tnt_server.log
            maxBytes: 100000000
            backupCount: 9
            formatter: detailed

        # Handler to write logs into console
        console:
            level: !!python/name:logging.INFO
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: basic
            filters: [patternfilter]

        # Handler to send logs to the socket
        socket:
            class: logging.handlers.SocketHandler
            host: !!python/name:socket_logger.socket_server.LOG_SERVER_ADDRESS
            port: !!python/name:socket_logger.socket_server.LOG_SERVER_PORT

    formatters:
        # Log file formatter
        detailed:
            format: '%(asctime)s %(levelname)7s: %(threadName)10s %(name)10s -> %(funcName)20s %(lineno)5d - %(message)s'

        # Console log formatter
        basic:
            (): colorlog.ColoredFormatter
            log_colors:
                DEBUG: cyan
                INFO: green
                WARNING: yellow
                ERROR: red
                CRITICAL: red, bg_white
            format: '%(log_color)s %(asctime)s.%(msecs)03d %(levelname)s %(name)-8s%(reset)s %(message)s'
            datefmt: '%H:%M:%S'

    filters:
       patternfilter:
           (): tntserver.loggingfilters.PatternFilter
           ignore: [still, output_state]
